name:                assrock
version:             0.1.0.0
github:              "homam/assrock"
license:             BSD3
author:              "Homam"
maintainer:          "example@example.com"
copyright:           "2018 Homam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/homam/assrock#readme>

dependencies:
- base >= 4.7 && < 5
- persistent
- persistent-postgresql
- persistent-template
- persistent-postgresql-json
- aeson
- aeson-pretty
- monad-logger
- bytestring
- text
- transformers
- containers
- http-types
- scotty
- wai
- wai-extra
- mtl
- resource-pool
- monad-control
- utf8-string
- base64-bytestring
- time
- http-client
- network-uri
- hedis
- unordered-containers
- case-insensitive
- http-client-tls
- http-conduit
- postgresql-simple
- time
- uri-encode
- AES
- cryptocipher
- cryptonite
- hspec
- HUnit
- hspec-wai
- hspec-expectations
- safe-exceptions
- random
- async
- http-client-tls
- haquery
- unliftio-core

library:
  source-dirs: src

executables:
  assrock-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assrock

tests:
  assrock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assrock
